<?php

namespace App\Http\Middleware;

use App\CodeResponse;
use App\Exceptions\BusinessException;
use Illuminate\Auth\Middleware\Authenticate as Middleware;
use Illuminate\Http\Request;

class Authenticate extends Middleware
{
    /**
     * @param Request $request
     * @return string|null
     */
    protected function redirectTo(Request $request): ?string
    {
        if (!$request->expectsJson()) {
            return route('login');
        }
    }


    /**
     * 验证失败
     * @param  \Illuminate\Http\Request  $request
     * @param  array  $guards
     * @throws BusinessException
     * @throws \Illuminate\Auth\AuthenticationException
     */
    protected function unauthenticated($request, array $guards)
    {

        if ($request->expectsJson()) {
            throw new BusinessException(CodeResponse::UN_LOGIN);
        }
        parent::unauthenticated($request, $guards); // TODO: Change the autogenerated stub
    }
}
